### ISSUE TITLE
1.10 - android app crash - FuseJS/Storage - breaks on a File.Exists call from Uno

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/uno#129] opened 2018-11-15 15:31 UTC
Hi guys,

Storage.read crashes android app (crashing devices: low-end Android 6, low Android 8.1; works on medium-end Android 6).

I've compiled from latest Uno and using latest Fuselibs.

Repeatable test code:
```javascript
<App>
	<JavaScript>

	var Storage = require('FuseJS/Storage');
	Storage.read("test.txt")
		.then(function(str) {
			console.log("str: " + str);
		},function(error){
			console.log("Error: " + error);
		});

	</JavaScript>
</App>
```
I've narrowed it down to File.Exists causing the crash when using ```Storage.read```:
https://github.com/fuse-open/fuselibs/blob/master/Source/Fuse.Storage/ApplicationDir.uno#L36

Strangely, ```Storage.readSync``` seems to be working fine.

**Comment by kusma** [comment] 2018-11-15 17:12
Is this bug new in 1.10, or can you also reproduce it on 1.9?

**Comment by AndrewEQ** [comment] 2018-11-15 17:17
Yeah, I believe its a new 1.10 bug; I haven't retested in 1.9 but I think I would have noticed it in 1.9, else I wouldn't have been able to get very far with my app :D

**Comment by AndrewEQ** [comment] 2018-11-16 08:36
Ok, I did more testing and here are my notes:

1. FileSystem.read also breaks if the file does not exist instead of throwing an exception
2. FileSystem.exists (async) doesn't break! Strange, so I checked the underlying code and the only difference I can think of is the structure? In FileSystem.exists, a "RunTask" is used and in the Storage.read a Promise is used.

FileSystem.exists
```
public Future<bool> Exists(string path)
{
    return RunTask<string, bool>(ExistsSync, path);
}
```

Storage.read
```
public static Future<string> ReadAsync(string filename)
{
    return Promise<string>.Run(new ReadClosure(filename).Invoke);
}
```



Test app
```
<App>
	<JavaScript>

		var FileSystem = require("FuseJS/FileSystem");
		var Storage = require('FuseJS/Storage');

		var filename = "testfile1.tmp";
		var path = FileSystem.dataDirectory + "/" + filename;


		FileSystem.exists(path)
		.then(function(x) {
			console.log(x ? "it's there! =)" : "it's missing :/");
		}, function(error) {
			console.log("Unable to check if file exists");
		});



		FileSystem.writeTextToFile(path, "hello world")
		.then(function() {
			return FileSystem.readTextFromFile(path);
		})
		.then(function(text) {
			console.log("The read file content was: " + text);
		})
		.catch(function(error) {
			console.log("Unable to read file due to error:" + error);
		});


		Storage.read(filename)
		.then(function(str) {
			console.log("str: " + str);
		},function(error){
			console.log("Error: " + error);
		});



		FileSystem.readTextFromFile(FileSystem.dataDirectory + "/" + "testfile2.tmp")
		.then(function(contents) {
			console.log('contents');
			console.log(contents);
		}, function(error) {
			console.log('error');
			console.log(error);
		});
	</JavaScript>
</App>

```

**Comment by AndrewEQ** [comment] 2018-11-16 08:37
Oh yeah, I retested on 1.9 and it doesn't crash.

**Comment by kusma** [comment] 2018-11-16 13:33
TBH, this sounds a bit like the good old "throwing exceptions inside V8 crashes"-problem. So my *guess* is that some exception has been introduced... Would it be possible for you to debug this a bit, and try to confirm? If so, it might be possible to at least get an emergency-switch to disable the native stacktrace-stuff, so people can choose what what is broken? :P

**Comment by kusma** [comment] 2018-11-16 13:34
I'm talking about this issue: https://github.com/fuse-open/fuselibs/issues/679

**Comment by AndrewEQ** [comment] 2018-11-16 17:40
Lol, so what happened between 1.9 and 1.10 to cause this crashing(https://github.com/fuse-open/fuselibs/issues/679)? Can't "we" fix that rather? XD

Anyhoo, I did do further debugging and can confirm its the throwing of the exception here(or read below): https://github.com/fuse-open/fuselibs/blob/master/Source/Fuse.Storage/ApplicationDir.uno#L52
I returned true from the TryRead function and it didn't crash, as soon as I returned false, the app died.
```javascript
		public static string Read(string filename)
		{
			string content;
			if (TryRead(filename, out content))
				return content;
			else
				throw new Exception("File does not exist.");
		}
```

FileSystem.exists doesn't throw an exception when the file doesn't exist, it just returns the result of the File.Exists and thats why it didn't cause a crash: https://github.com/fuse-open/fuselibs/blob/master/Source/Fuse.FileSystem/FileSystemOperations.uno#L75
```javascript
		public bool ExistsSync(string path)
		{
			// File.Exists also returns true special files like named pipes etc in .NET (mono and MS implementation)
			// and also in uBase::Disk->IsFile. This makes the following work for all file system entries:
			return File.Exists(path) || Directory.Exists(path);
		}
```

**Comment by AndrewEQ** [comment] 2018-12-10 10:52
@mortend cool, I will try it out sometime soon.

**Comment by AndrewEQ** [comment] 2018-12-24 16:08
Thanks @mortend it seems have resolved the issue and is working so far, will be doing more testing in the New Year and will keep ya posted.

**Comment by AndrewEQ** [comment] 2019-01-23 11:56
@mortend every now and then, after an export to iOS, I get this kind of error:

```
PROCESS_STOPPED
* thread #8, stop reason = EXC_BREAKPOINT (code=1, subcode=0x23e02a3a4)
  * frame #0: 0x000000023e02a3a4 JavaScriptCore`WTFCrashWithInfo(int, char const*, char const*, int, unsigned long long, unsigned long long, unsigned long long) + 12
    frame #1: 0x000000023e98a758 JavaScriptCore`JSC::JSObject::toPrimitive(JSC::ExecState*, JSC::PreferredPrimitiveType) const + 3484
    frame #2: 0x000000023e9e04e0 JavaScriptCore`JSC::objectConstructorDefineProperty(JSC::ExecState*) + 448
    frame #3: 0x000000023e08dbac JavaScriptCore`llint_entry + 32652
    frame #4: 0x000000023e08d134 JavaScriptCore`llint_entry + 29972
    frame #5: 0x000000023e085a1c JavaScriptCore`vmEntryToJavaScript + 300
    frame #6: 0x000000023e6fd3f0 JavaScriptCore`JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 424
    frame #7: 0x000000023e8b4068 JavaScriptCore`JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 172
    frame #8: 0x000000023e0bb284 JavaScriptCore`JSObjectCallAsFunction + 368
    frame #9: 0x00000001045dad98 ShweetSpot`g::Fuse::Scripting::JavaScriptCore::JSObjectRef::CallAsFunction(__this=<unavailable>, ctx=<unavailable>, thisObject=<unavailable>, arguments=<unavailable>, onException=0x0000000282982f30) at Fuse.Scripting.JavaScriptCore.g.cpp:1493 [opt]
    frame #10: 0x00000001045da70c ShweetSpot`g::Fuse::Scripting::JavaScriptCore::Function__Call_fn(__this=0x00000002806a9320, context=<unavailable>, args=0x0000000282fe0ae0, __retval=0x000000016bd4eb48) at Fuse.Scripting.JavaScriptCore.g.cpp:950 [opt]
    frame #11: 0x00000001045b9070 ShweetSpot`g::Fuse::Scripting::Context::ObjectDefineProperty(g::Fuse::Scripting::Object*, uString*, uDelegate*, uDelegate*, bool, bool) [inlined] g::Fuse::Scripting::Function::Call(this=0x00000002806a9320, context=<unavailable>, args=<unavailable>) at Fuse.Scripting.Function.h:32 [opt]
    frame #12: 0x00000001045b9058 ShweetSpot`g::Fuse::Scripting::Context::ObjectDefineProperty(this=0x00000002831f12b0, obj=0x00000002806a9440, name=0x0000000281fb4200, getProperty=0x0000000282a20f50, setProperty=0x0000000000000000, enumerable=false, configurable=false) at Fuse.Scripting.g.cpp:1315 [opt]
    frame #13: 0x00000001045cc4b8 ShweetSpot`g::Fuse::Scripting::JavaScript::LazyObservableProperty::ctor_1(this=0x0000000282a20f00, w=<unavailable>, obj=0x00000002806a9440, p=<unavailable>, c=0x00000002831f12b0) at Fuse.Scripting.JavaScript.g.cpp:1979 [opt]
    frame #14: 0x00000001045c87a8 ShweetSpot`g::Fuse::Scripting::JavaScript::ClassInstance::EnsureRooted(g::Fuse::Scripting::Context*) [inlined] g::Fuse::Scripting::JavaScript::LazyObservableProperty::New2(w=0x0000000281f56b00, obj=0x00000002806a9440, p=<unavailable>, c=<unavailable>) at Fuse.Scripting.JavaScript.g.cpp:1992 [opt]
    frame #15: 0x00000001045c8788 ShweetSpot`g::Fuse::Scripting::JavaScript::ClassInstance::EnsureRooted(this=0x0000000282a20230, context=0x00000002831f12b0) at Fuse.Scripting.JavaScript.g.cpp:755 [opt]
    frame #16: 0x00000001045d2e40 ShweetSpot`g::Fuse::Scripting::JavaScript::RootableScriptModule__Evaluate_fn(__this=0x0000000283865200, c=0x00000002831f12b0, result=0x0000000282fe0de0) at Fuse.Scripting.JavaScript.g.cpp:4403 [opt]
    frame #17: 0x00000001045bd1cc ShweetSpot`g::Fuse::Scripting::Module::Evaluate1(g::Fuse::Scripting::Context*, uString*) [inlined] g::Fuse::Scripting::Module::Evaluate(this=<unavailable>, c=<unavailable>, result=<unavailable>) at Fuse.Scripting.Module.h:44 [opt]
    frame #18: 0x00000001045bd1b4 ShweetSpot`g::Fuse::Scripting::Module::Evaluate1(this=0x0000000283865200, c=0x00000002831f12b0, id=0x0000000000000000) at Fuse.Scripting.g.cpp:2981 [opt]
    frame #19: 0x00000001045cd61c ShweetSpot`g::Fuse::Scripting::JavaScript::ModuleInstance::EvaluateModule(this=0x0000000282e0b3c0, context=0x00000002831f12b0) at Fuse.Scripting.JavaScript.g.cpp:2302 [opt]
    frame #20: 0x00000001045cd2ec ShweetSpot`g::Fuse::Scripting::JavaScript::ModuleInstance::Evaluate(this=0x0000000282e0b3c0, context=0x00000002831f12b0) at Fuse.Scripting.JavaScript.g.cpp:2286 [opt]
    frame #21: 0x00000001045d50b8 ShweetSpot`g::Fuse::Scripting::JavaScript::ThreadWorker::RunOnce(this=<unavailable>, context=0x00000002831f12b0) at Fuse.Scripting.JavaScript.g.cpp:5401 [opt]
    frame #22: 0x00000001045d4fcc ShweetSpot`g::Fuse::Scripting::JavaScript::ThreadWorker::RunInner(this=0x0000000281f56b00, context=0x00000002831f12b0) at Fuse.Scripting.JavaScript.g.cpp:5374 [opt]
    frame #23: 0x00000001045d4df8 ShweetSpot`g::Fuse::Scripting::JavaScript::ThreadWorker::Run(this=0x0000000281f56b00) at Fuse.Scripting.JavaScript.g.cpp:5334 [opt]
    frame #24: 0x0000000104542840 ShweetSpot`g::Uno::Threading::Thread::ThreadMain(thread=0x0000000281f56a80) at Uno.Threading.g.cpp:2789 [opt]
    frame #25: 0x0000000104542900 ShweetSpot`_ThreadFunc(arg=<unavailable>) at Uno.Threading.g.cpp:65 [opt]
    frame #26: 0x00000002369a12fc libsystem_pthread.dylib`_pthread_body + 128
    frame #27: 0x00000002369a125c libsystem_pthread.dylib`_pthread_start + 48
    frame #28: 0x00000002369a4d08 libsystem_pthread.dylib`thread_start + 4
```

**Comment by ckarmy** [comment] 2019-01-23 20:37
This solve the Android crash problems

**Comment by Hotschmoe** [comment] 2019-01-26 08:11
I tried the above Source change to mortend's fork but I am still receiving the following crash when launching on android

`Launching activity 'SASi'

Running logcat on 380f7dc7

01-26 01:08:22.286  1079  1726 I ActivityManager: Start proc 27390:com.apps.sasi/u0a170 for activity com.apps.sasi/.SASi
01-26 01:08:22.307 27390 27390 I zygote  : Late-enabling -Xcheck:jni
01-26 01:08:22.405 27390 27390 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-26 01:08:22.408 27390 27390 I FirebaseInitProvider: FirebaseApp initialization successful
01-26 01:08:22.420 27390 27390 D SASi    : SDK: 27
01-26 01:08:22.439 27390 27416 I FA      : App measurement is starting up, version: 12211
01-26 01:08:22.440 27390 27416 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
01-26 01:08:22.440 27390 27416 I FA      : To enable faster debug mode event logging run:
01-26 01:08:22.440 27390 27416 I FA      :   adb shell setprop debug.firebase.analytics.app com.apps.sasi
01-26 01:08:22.459 27390 27390 I Adreno  : QUALCOMM build                   : 9c9b012, I92eb381bc9
01-26 01:08:22.459 27390 27390 I Adreno  : Build Date                       : 12/31/17
01-26 01:08:22.459 27390 27390 I Adreno  : OpenGL ES Shader Compiler Version: EV031.22.00.01
01-26 01:08:22.459 27390 27390 I Adreno  : Local Branch                     :
01-26 01:08:22.459 27390 27390 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.4.R1.08.00.00.309.049
01-26 01:08:22.459 27390 27390 I Adreno  : Remote Branch                    : NONE
01-26 01:08:22.459 27390 27390 I Adreno  : Reconstruct Branch               : NOTHING
01-26 01:08:22.462 27390 27390 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
01-26 01:08:22.464 27390 27390 I zygote  : android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
01-26 01:08:22.578 27390 27390 D AutoManageHelper: starting AutoManage for client 0 false null
01-26 01:08:22.593 27390 27390 W MediaPlayer: Use of stream types is deprecated for operations other than volume control
01-26 01:08:22.593 27390 27390 W MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-26 01:08:22.595 27390 27390 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
01-26 01:08:22.595 27390 27390 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
01-26 01:08:22.595   815  1868 D NuPlayerDriver: NuPlayerDriver(0xecdbd580) created, clientPid(27390)
01-26 01:08:22.603 27390 27390 D AutoManageHelper: onStart true {0=com.google.android.gms.common.api.internal.zzi$zza@b8adffb}
01-26 01:08:22.625 27390 27440 D OpenGLRenderer: HWUI GL Pipeline
01-26 01:08:22.662 27390 27440 I OpenGLRenderer: Initialized EGL, version 1.4
01-26 01:08:22.662 27390 27440 D OpenGLRenderer: Swap behavior 2
01-26 01:08:22.695 27390 27390 W AudioManager: Use of stream types is deprecated for operations other than volume control
01-26 01:08:22.695 27390 27390 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-26 01:08:22.698  1079  2982 I MediaFocusControl: requestAudioFocus() from uid/pid 10170/27390 clientId=android.media.AudioManager@41b3cf callingPack=com.apps.sasi req=1 flags=0x0 sdk=26
01-26 01:08:22.705 27390 27397 I zygote  : Do partial code cache collection, code=30KB, data=21KB
01-26 01:08:22.706 27390 27397 I zygote  : After code cache collection, code=30KB, data=21KB
01-26 01:08:22.706 27390 27397 I zygote  : Increasing code cache capacity to 128KB

01-26 01:08:22.751 27390 27463 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7 in tid 27463 (Thread-4), pid 27390 (com.apps.sasi)
01-26 01:08:22.760 27390 27466 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
01-26 01:08:22.763 27390 27466 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
01-26 01:08:22.765 27390 27411 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
01-26 01:08:22.767 27390 27411 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
01-26 01:08:22.774 27390 27411 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
01-26 01:08:22.775 27390 27411 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000

01-26 01:08:22.819   836   836 I /system/bin/tombstoned: received crash request for pid 27390
01-26 01:08:22.820 27470 27470 I crash_dump32: performing dump of process 27390 (target tid = 27463)
01-26 01:08:22.822 27470 27470 F DEBUG   : pid: 27390, tid: 27463, name: Thread-4  >>> com.apps.sasi <<<

01-26 01:08:23.443  1079  2982 I ActivityManager: Process com.apps.sasi (pid 27390) has died: fore TOP
01-26 01:08:23.444  1079  1100 W zygote64: kill(-27390, 9) failed: No such process
01-26 01:08:23.447   695   695 I Zygote  : Process 27390 exited due to signal (11)

01-26 01:08:23.480  1079  1105 W ActivityManager: setHasOverlayUi called on unknown pid: 27390
01-26 01:08:23.490  1079  1100 W zygote64: kill(-27390, 9) failed: No such process
01-26 01:08:23.490  1079  1100 I zygote64: Successfully killed process cgroup uid 10170 pid 27390 in 45ms

Unknown Logcat Error: raised from 'adb -s 380f7dc7 logcat '`

**Comment by Hotschmoe** [comment] 2019-01-26 08:15
the log was similar to the non-forked Source build but not the exact same as the one above

**Comment by mortend** [comment] 2019-01-28 13:58
Closing the issue because it sounds like the Android crashes have been fixed.

**Closed by mortend** 2019-01-28 13:58 UTC
