### ISSUE TITLE
Testing - macOS Catalina - iOS13 - Run Fail

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/uno#210] opened 2019-07-29 08:33 UTC
Hey there,

`uno build -t=ios --run` successfully deployed the app but didn't run it, the error message returned after the build and deploy was:

```
Error 0xe800007f: Device doesn't support wireless sync.
```

**Comment by ichan-mb** [comment] 2019-07-29 08:54
I think the problem is on `ios-deploy` command. I see an issue has been raised in `ios-deploy` repo [here](https://github.com/ios-control/ios-deploy/pull/385) and has been merged. maybe we can use the latest version of `ios-deploy`

just google up, Flutter has the same issue as describe [here](https://github.com/flutter/flutter/issues/33909)  and replacing `ios-deploy` cmd with this one `wget https://raw.githubusercontent.com/kangwang1988/kangwang1988.github.io/master/others/ios-deploy` resolved the issue

**Comment by mortend** [comment] 2019-07-29 09:40
Good catch!

We should probably switch to `ios-deploy` (instead of `"@(Base.Directory)/bin/ios-deploy"`) in https://github.com/fuse-open/uno/blob/master/lib/UnoCore/Targets/iOS/run.sh.

If https://www.npmjs.com/package/ios-deploy includes the fix, we can probably add `ios-deploy` to `dependencies` in `package.json`, and let npm take care of installing things.

**Comment by mortend** [comment] 2019-07-29 09:53
The beta version on NPM should include the fix - `npm install ios-deploy@beta --save`.

**Comment by ichan-mb** [comment] 2019-07-30 02:30
Yeah, sounds a good idea!

**Comment by mortend** [comment] 2019-09-17 10:53
Resolved by #226. Closing issue.

**Closed by mortend** 2019-09-17 10:53 UTC

**Comment by AndrewEQ** [comment] 2019-09-18 06:25
@mortend just tried it out again with latest Uno, and it doesn't seem to have permission to run the script, I'm using the compiled version of Uno:
```
run.sh: line 27: /Users/andrewq/www/github/fuse-open/uno/lib/UnoCore/prebuilt/iOS/bin/ios-deploy: Permission denied
```

**Comment by mortend** [comment] 2019-09-18 06:39
That's weird, the latest version of Uno runs `ios-deploy` from PATH and there are no longer any references to `[...]/lib/UnoCore/prebuilt/iOS/bin/ios-deploy` in our source code. Also, `ios-deploy` is executed on line 37 and 39 (not 27) in the latest version of the script, so it looks like you're not using the latest version.

- Have you added `/Users/andrewq/www/github/fuse-open/uno/lib/UnoCore/prebuilt/iOS/bin` to your PATH? If you have, you should remove it from PATH so the script can find the npm-installed version of `ios-deploy`.
- Does it work if you `uno clean` your project and rebuild?
- How did you install Uno?

**Comment by AndrewEQ** [comment] 2019-09-18 12:38
Ok, so to recap, it was my use of bolav's cocoa pods module(https://github.com/bolav/fuse-cocoapods) that was the issue. I couldn't get the built-in cocoa pods working though, so replaced `@(Base.Directory)/bin/ios-deploy` with just `ios-deploy` in the run.sh ... then my next issue was with ios-deploy itself, couldn't install via npm because it didn't have permission to write to `/usr/local/lib/node_modules`, so I went with building ios-deploy from source via `xcodebuild` command, then creating a hard sym link from `build/release/ios-deploy` to `/usr/local/bin/ios-deploy`.

Only thing now is that the run works but detaches itself right after deploying, so can't log anything:
```
(lldb)     command script add -f fruitstrap_10fc02003527248efce104c0b827f890aafabb34.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_10fc02003527248efce104c0b827f890aafabb34.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_10fc02003527248efce104c0b827f890aafabb34.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_10fc02003527248efce104c0b827f890aafabb34.safequit_command safequit
(lldb)     connect
(lldb)     run
success
(lldb)     safequit
Process 2111 detached
```

**Comment by mortend** [comment] 2019-09-19 04:56
Thanks for sharing the recap!

I just tested `ios-deploy` on my machine, and things work with logging and everything. I'm on iOS 12.4, macOS 10.14.5 and Xcode 9.4.1.
