### ISSUE TITLE
64bit Uno Beta Feedback

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/uno#194] opened 2019-06-18 15:24 UTC
Was testing with latest Uno + Fuselibs:
`npm install https://ci.appveyor.com/api/buildjobs/uuoairgtdvd1sn0f/artifacts/fuse-open-uno-1.11.1.tgz`

Both apps were able to launch, its only when they tried to load a page with: a timeline animation, grid layout and some local images; then it crashed.

First droid crash with (64bit):

```
06-18 16:53:11.234  7544  7544 E libEGL  : eglMakeCurrent:809 error 3002 (EGL_BAD_ACCESS)
06-18 16:53:11.244  7544  7544 W MainActivity: GLHelper::MakeCurrent: Unable to make EGL context current:12290
06-18 16:53:11.339  7544  7544 D AndroidRuntime: Shutting down VM
06-18 16:53:11.379  7544  7544 E AndroidRuntime: FATAL EXCEPTION: main
06-18 16:53:11.379  7544  7544 E AndroidRuntime: Process: com.shweetspot.android, PID: 7544
06-18 16:53:11.379  7544  7544 E AndroidRuntime: java.lang.RuntimeException: Unhandled c++ error
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at com.Bindings.ExternedBlockHost.callUno_Uno_Platform_AndroidDisplay_OnFrameCallback58(Native Method)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at com.foreign.Uno.Platform.AndroidDisplay$1.doFrame(AndroidDisplay.java:55)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
06-18 16:53:11.379  7544  7544 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

Second droid crashed with (32bit):
```
06-18 16:55:10.494  9521  9521 E libEGL  : eglMakeCurrent:809 error 3002 (EGL_BAD_ACCESS)
06-18 16:55:10.498  9521  9521 W MainActivity: GLHelper::MakeCurrent: Unable to make EGL context current:12290
06-18 16:55:10.586  9521  9521 D AndroidRuntime: Shutting down VM
06-18 16:55:10.744  9521  9521 E AndroidRuntime: FATAL EXCEPTION: main
06-18 16:55:10.744  9521  9521 E AndroidRuntime: Process: com.shweetspot.android, PID: 9521
06-18 16:55:10.744  9521  9521 E AndroidRuntime: java.lang.RuntimeException: Unhandled c++ error
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at com.Bindings.ExternedBlockHost.callUno_Fuse_Platform_SystemUI_cppOnConfigChanged110(Native Method)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at com.foreign.Fuse.Platform.SystemUI$4.onLayoutChange(SystemUI.java:255)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.View.layout(View.java:16654)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5471)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.View.layout(View.java:16645)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5471)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.View.layout(View.java:16645)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5471)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.View.layout(View.java:16645)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5471)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.View.layout(View.java:16645)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5471)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2694)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.View.layout(View.java:16645)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5471)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
06-18 16:55:10.744  9521  9521 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

```

**Comment by mortend** [comment] 2019-06-19 04:21
Ouch, this sounds like a release blocker.

Any chance you could share the piece of your project that trigger the problem? (Slack or email)

Then I'll see if I can reproduce on my devices.

Thanks.

**Comment by mortend** [comment] 2019-06-19 09:53
Update: I've reproduced the problem and found a workaround. Should be fixed soon.

**Comment by kusma** [comment] 2019-06-19 11:21
I'm a bit embarrassed I didn't notice this during code-review, since I was involved in the conceptualization of that pile of crap code.

**Closed** 2019-06-19 11:20 UTC
